# Generated by Django 4.0.1 on 2022-01-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovei',
            name='disponbilidade',
            field=models.CharField(choices=[('A', 'Alugado'), ('C', 'Comprado'), ('D', 'Disponível')], default='D', max_length=1),
        ),
    ]
