# Generated by Django 4.0.1 on 2022-01-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_imovei_disponbilidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovei',
            old_name='disponbilidade',
            new_name='disponibilidade',
        ),
    ]
