# Generated by Django 4.0.1 on 2022-01-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_rename_disponbilidade_imovei_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovei',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
    ]
